FROM rustlang/rust:nightly-bookworm AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config libssl-dev libpq-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

ENV RUSTFLAGS="-Z unstable-options"

COPY . .

RUN cargo build --release --bin book

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates libssl3 libpq5 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/app/target/release/book .
CMD ["./book"]