version: "3.9"

x-common-config: &default-config
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  volumes:
    - ./data:/app/data
    - ./logs:/app/logs
  env_file:
    - .env
  networks:
    - polymarket-backend

services:
  polymarket-live-15m-crypto-data-collector:
    <<: *default-config
    container_name: polymarket-live-15m-crypto-data-collector
    command: uv run python -m services.15m.entrypoint

  polymarket-live-1h-crypto-data-collector:
    <<: *default-config
    container_name: polymarket-live-1h-crypto-data-collector
    command: uv run python -m services.1h.entrypoint

  polymarket-live-4h-crypto-data-collector:
    <<: *default-config
    container_name: polymarket-live-4h-crypto-data-collector
    command: uv run python -m services.4h.entrypoint

  polymarket-live-daily-crypto-data-collector:
    <<: *default-config
    container_name: polymarket-live-daily-crypto-data-collector
    command: uv run python -m services.Daily.entrypoint

networks:
  polymarket-backend:
    external: true