[project]
name = "fetch-polymarket-live-15m"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.13.2",
    "dotenv>=0.9.9",
    "loguru>=0.7.3",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "pyarrow>=21.0.0",
    "pytz>=2025.2",
    "questdb>=4.1.0",
    "websockets>=15.0.1",
]
