[package]
name = "connectors"
edition.workspace = true
version.workspace = true

[dependencies]
tokio.workspace = true
rust_decimal_macros.workspace = true
crc32fast.workspace = true
chrono.workspace = true
dotenv.workspace = true
questdb-rs.workspace = true
deadpool-postgres.workspace = true
tokio-postgres.workspace = true
exchanges.workspace = true
tokio-util.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
rust_decimal.workspace = true

exchanges-common.workspace = true

[lints]
workspace = true